package com.techtornado.erggenerator.presentation

val mockAnswers = listOf(
    // Environmental (E) - Climate Change & Emissions (20)
    Pair("What was your total Scope 1 greenhouse gas emissions in the reporting year (in tonnes of CO2e)?", "Our total Scope 1 emissions were 500 tonnes of CO2e."),
    Pair("What was your total Scope 2 greenhouse gas emissions in the reporting year (in tonnes of CO2e)?", "Our total Scope 2 emissions were 300 tonnes of CO2e."),
    Pair("Do you have a target for reducing greenhouse gas emissions?", "Yes, we aim to reduce our combined Scope 1 and 2 emissions by 25% by 2030 (baseline year 2022)."),
    Pair("What initiatives have you implemented to reduce your energy consumption?", "We have upgraded our lighting to LED, improved insulation, and optimized our HVAC systems."),
    Pair("What percentage of your energy consumption comes from renewable sources?", "Currently, 15% of our energy consumption is from renewable sources."),
    Pair("Do you track your Scope 3 greenhouse gas emissions?", "Yes, we are in the process of refining our Scope 3 emissions calculations, focusing on purchased goods and services and business travel."),
    Pair("What are your strategies for mitigating climate-related risks to your business?", "We are conducting climate risk assessments and implementing adaptation measures in our supply chain and operations."),
    Pair("Do you participate in any carbon offset programs?", "We are currently evaluating carbon offset opportunities."),
    Pair("What is your company's energy intensity (e.g., energy consumed per unit of production)?", "Our energy intensity was 0.05 MWh per unit produced."),
    Pair("Do you report your climate-related financial disclosures according to the TCFD framework?", "We are working towards full alignment with the TCFD recommendations."),
    Pair("What is your company's water withdrawal in the reporting year (in cubic meters)?", "Our total water withdrawal was 2,000 cubic meters."),
    Pair("What measures do you have in place to conserve water?", "We have implemented water-efficient fixtures and optimized our industrial processes to reduce water usage."),
    Pair("Do you operate in water-stressed areas?", "A portion of our supply chain operates in areas identified as having medium-high water stress."),
    Pair("What is your company's total waste generated in the reporting year (in tonnes)?", "We generated 400 tonnes of waste."),
    Pair("What percentage of your waste was recycled?", "45% of our waste was recycled."),
    Pair("What initiatives do you have to reduce waste sent to landfill?", "We have implemented enhanced recycling programs and are exploring opportunities for waste reduction at the source."),
    Pair("Do you have policies to prevent pollution of air, water, and land?", "Yes, our environmental management system includes policies and procedures for pollution prevention."),
    Pair("What measures do you take to minimize your impact on biodiversity?", "We conduct environmental impact assessments for new projects and strive to avoid or mitigate impacts on sensitive ecosystems."),
    Pair("Are you compliant with all applicable environmental regulations?", "Yes, we are committed to full compliance with all relevant environmental laws and regulations."),
    Pair("Do you have an environmental management system (e.g., ISO 14001 certified)?", "Yes, our primary manufacturing facility is ISO 14001 certified."),

    // Environmental (E) - Resource Management & Biodiversity (10)
    Pair("What is your consumption of key raw materials in the reporting year?", "Our consumption of primary raw material X was Y tonnes."),
    Pair("Do you prioritize the use of sustainable or recycled materials?", "Yes, we are actively exploring and increasing our use of recycled and sustainably sourced materials."),
    Pair("What efforts do you make to ensure the sustainability of your supply chain regarding natural resources?", "We engage with our suppliers to promote sustainable practices and conduct audits where necessary."),
    Pair("Do your operations impact any protected or high-biodiversity areas?", "We have assessed our operations and do not have direct significant impacts on protected or high-biodiversity areas."),
    Pair("What measures do you take to mitigate any indirect impacts on biodiversity through your value chain?", "We are working with our suppliers to understand and mitigate their potential impacts on biodiversity."),
    Pair("Do you have any programs focused on ecological restoration or conservation?", "We support a local reforestation initiative in the region where we operate."),
    Pair("What is your approach to managing packaging materials?", "We are focused on reducing the amount of packaging used and increasing the recyclability of our packaging."),
    Pair("Do you track the use of hazardous materials in your operations?", "Yes, we meticulously track and manage the use and disposal of hazardous materials according to regulations."),
    Pair("What initiatives do you have to promote a circular economy approach?", "We are exploring product design for durability and recyclability, as well as potential take-back programs."),
    Pair("How do you engage with stakeholders on environmental issues?", "We engage with stakeholders through regular communication, including our sustainability reports and community meetings."),

    // Social (S) - Labor Practices & Human Rights (20)
    Pair("What is the total number of employees in your company?", "We have 500 employees globally."),
    Pair("What is the gender breakdown of your workforce (percentage male/female)?", "Our workforce is currently 55% male and 45% female."),
    Pair("What is your employee turnover rate?", "Our employee turnover rate for the past year was 15%."),
    Pair("Do you have a formal health and safety policy in place?", "Yes, we have a comprehensive health and safety policy that is regularly reviewed and updated."),
    Pair("What was your lost-time injury frequency rate (LTIFR) in the reporting year?", "Our LTIFR was 2.5 per million hours worked."),
    Pair("What training and development opportunities do you provide to your employees?", "We offer a range of training programs, including technical skills development, leadership training, and safety certifications."),
    Pair("Do you conduct regular employee satisfaction surveys?", "Yes, we conduct annual employee satisfaction surveys to gather feedback and identify areas for improvement."),
    Pair("What is your approach to ensuring fair wages and benefits?", "We regularly benchmark our compensation and benefits against industry standards to ensure competitiveness and fairness."),
    Pair("Do you have policies in place to prevent discrimination and harassment?", "Yes, we have a strict anti-discrimination and anti-harassment policy and provide regular training on these topics."),
    Pair("Do you have a grievance mechanism for employees to report concerns?", "Yes, we have a confidential grievance mechanism that allows employees to report concerns without fear of retaliation."),
    Pair("Do you conduct human rights due diligence in your operations and supply chain?", "Yes, we are implementing a human rights due diligence process to identify and address potential risks."),
    Pair("Do you have policies to prevent forced labor and child labor in your supply chain?", "Yes, our supplier code of conduct explicitly prohibits forced labor and child labor, and we conduct audits to ensure compliance."),
    Pair("What percentage of your key suppliers are assessed for human rights risks?", "Currently, 60% of our key suppliers have been assessed for human rights risks."),
    Pair("Do you provide training on human rights for your employees and suppliers?", "Yes, we provide human rights awareness training to relevant employees and engage with our suppliers on these issues."),
    Pair("What measures do you take to ensure the health and safety of workers in your supply chain?", "We include health and safety requirements in our supplier contracts and conduct audits to monitor compliance."),
    Pair("Do you engage with trade unions or other worker representatives?", "We engage with relevant trade unions and worker representatives in locations where our employees are unionized."),
    Pair("What is your approach to promoting diversity and inclusion in the workplace?", "We have a DE&I strategy that includes inclusive hiring practices, employee resource groups, and diversity training."),
    Pair("What is the representation of women in management positions (percentage)?", "Currently, 30% of our management positions are held by women."),
    Pair("What is the representation of ethnic minorities in your workforce (percentage)?", "X% of our workforce identifies as belonging to ethnic minority groups."),
    Pair("Do you have a policy on equal opportunities?", "Yes, we are an equal opportunities employer and are committed to creating an inclusive workplace."),

    // Social (S) - Community Engagement & Customer Responsibility (10)
    Pair("Do you have a community engagement strategy?", "Yes, our community engagement strategy focuses on supporting education and environmental sustainability initiatives in the areas where we operate."),
    Pair("What percentage of your pre-tax profits do you donate to charitable causes?", "We donate 1% of our pre-tax profits to charitable organizations."),
    Pair("Do you have volunteer programs for your employees?", "Yes, we encourage employee volunteering and provide paid time off for volunteer activities."),
    Pair("How do you engage with local communities to understand their needs and concerns?", "We engage with local communities through regular meetings, community forums, and partnerships with local organizations."),
    Pair("What measures do you have in place to ensure product safety?", "We have rigorous product testing and quality control processes in place to ensure the safety of our products."),
    Pair("Do you have a customer data privacy policy?", "Yes, we have a comprehensive data privacy policy that complies with all applicable regulations."),
    Pair("How do you handle customer complaints and feedback?", "We have a dedicated customer service team and a formal process for handling and resolving customer complaints."),
    Pair("Do you conduct customer satisfaction surveys?", "Yes, we regularly conduct customer satisfaction surveys to gather feedback on our products and services."),
    Pair("What is your approach to responsible marketing and advertising?", "We adhere to ethical marketing practices and ensure that our advertising is transparent and truthful."),
    Pair("Do you consider the social impact of your products and services?", "Yes, we consider the social impact of our products and strive to develop solutions that benefit society."),

    // Governance (G) - Corporate Governance & Ethics (20)
    Pair("What is the structure of your board of directors (e.g., number of independent directors)?", "Our board of directors comprises 10 members, with 7 being independent directors."),
    Pair("Do you have a separate Chair and CEO?", "Yes, the roles of Chair and CEO are held by separate individuals."),
    Pair("How often does your board of directors meet?", "Our board of directors meets at least quarterly."),
    Pair("Do you have key board committees (e.g., Audit, Nomination, Compensation)?", "Yes, we have an Audit Committee, a Nomination and Governance Committee, and a Compensation Committee."),
    Pair("What are the key responsibilities of your board committees?", "The Audit Committee oversees financial reporting, the Nomination and Governance Committee oversees board composition and governance practices, and the Compensation Committee oversees executive compensation."),
    Pair("Do you have a code of ethics or conduct for your employees and directors?", "Yes, we have a comprehensive code of ethics and business conduct that applies to all employees and directors."),
    Pair("Do you provide ethics training to your employees?", "Yes, we provide regular ethics training to all employees."),
    Pair("Do you have a whistleblowing policy or mechanism for reporting ethical concerns?", "Yes, we have a confidential whistleblowing mechanism that allows employees to report concerns anonymously without fear of retaliation."),
    Pair("What is your approach to managing conflicts of interest?", "We have a policy on conflicts of interest that requires disclosure and appropriate management of any potential conflicts."),
    Pair("How do you ensure the independence and effectiveness of your internal audit function?", "Our internal audit function reports directly to the Audit Committee and operates independently."),
    Pair("What is your approach to risk management, including ESG-related risks?", "We have an enterprise risk management framework that includes the identification, assessment, and mitigation of ESG-related risks."),
    Pair("How do you integrate ESG factors into your business strategy and decision-making?", "We are increasingly integrating ESG considerations into our strategic planning processes and investment decisions."),
    Pair("How do you engage with your shareholders on ESG matters?", "We engage with our shareholders through our annual general meeting, investor relations activities, and dedicated ESG communications."),
    Pair("What are your policies on executive compensation?", "Our executive compensation policies are designed to align with the long-term interests of the company and its shareholders, and increasingly consider ESG performance."),
    Pair("Do you have a policy on anti-corruption and bribery?", "Yes, we have a strict anti-corruption and anti-bribery policy that prohibits such practices in all our operations."),
    Pair("Do you conduct due diligence on third parties to identify and mitigate corruption risks?", "Yes, we conduct risk-based due diligence on our key third-party relationships."),
    Pair("What measures do you take to ensure compliance with all applicable laws and regulations?", "We have a legal and compliance department that oversees our compliance obligations and provides regular training."),
    Pair("How do you ensure data privacy and security?", "We have robust data privacy and security policies and procedures in place to protect personal and sensitive information."),
    Pair("Do you have a cybersecurity strategy?", "Yes, we have a comprehensive cybersecurity strategy to protect our systems and data from cyber threats."),
    Pair("How do you ensure transparency and accountability in your ESG reporting?", "We strive for transparency in our ESG reporting by providing clear and accurate information, and we seek to align with recognized reporting frameworks.")
).map { Answer(it.first, it.second) }